language: python
python:
    - "3.5"
    - "3.6"
    
before_install:

install:
    - pip install -r requirements.txt
    - python setup.py install
    
    
script:
    - cd BioUtils/tests/
    - python tests_seq.py
    - python tests_io.py
    - python tests_residue.py
